sudo: false
language: ruby
cache: bundler
rvm:
- 2.5
- 2.6
- ruby-head
matrix:
  fast_finish: true
  allow_failures:
  - rvm: ruby-head
before_install:
- gem update --system
- gem install bundler
install:
- bundle install --jobs=3 --retry=3
script:
- bundle exec rspec
- bundle exec rubocop
- bundle exec fasterer
notifications:
  email: false
  slack:
    secure: mtfWWZthR1xe+vfHViVYno4doSLn9ENWoDumbhnoUcanYLlhqfnGY4U9Jde6QvoxKlcrAudOwyuD9DvwmtgEduhJbAi3fydHpeDGdL5opDqhQ7uaT8Gx93I9cYh/A4kf+GscUcFUqiRjH1IdT64ysfTVfBNXR9mxBNxGJa/qcE5Vq/N6loEtDabKoStknxBJPsKTzSWrx5zSa3a3q+fdLT4XTfxYisRiTssMEqfAY9vcHqYAwZ1KJk/mQ4GrWUNJPOvHrMW6u9/wKT2nv2Tfg6mM5G7q7WCF6AiZ6ZTlgVMyXylH+YhyEJpOSwhIkILDU+/1RR2JUKMb0aafps3+GHF7gPpubtPwMISj6Nb9mmoin68KD7xS/fs5X0BZZ7Hj6PBgrZJZLYunoQqKmE4MGp6UK2BwAS/cV1iv2QTxkN9NkJW2SSZCsEzK1SaZFIK8Z0R3Kvk6ntZhpNY4tR/RKXPbHYrGugZSNWhwyRYSwXSNOdkIbVgV2ukKPLvFi9t3mQuGIRbpgtvBB8sBx8xg72sH6wIuH7bh/lTjwWP08NPH666P/9a3BFwJSynS2JFE0g1kIrJDt8J85adhmxAm9Akybqmdti9C1UmLwOOT9Jtz1f+yy4Qf0+5umFiQ6ggVDbAS9OwK9t2tJKSzMmlSWgfufqKHDPHa9ATEgAe1l+M=
